title: BrickThrowers
description: A co-op game where players explore the deep sea.
theme: jekyll-theme-primer
baseurl: "/BrickThrowers"   
url: "https://SCCapstone.github.io"   

readme_index:
  enabled: true
